Repository kubernetes-sigs/nfs-ganesha-server-and-external-provisioner, pull requests merged in 2020-12, with the labels that each got.

#28 remove myself from maintainers
  deploy/helm/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#22 helm: support using image digest instead of tag
  deploy/helm/Chart.yaml
  deploy/helm/README.md
  deploy/helm/templates/statefulset.yaml
  deploy/helm/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#30 Setup automated builds using the release-tools
  .cloudbuild.sh
  .cloudbuild.yaml
  .travis.yml
  Dockerfile
  Makefile
  release-tools/.prow.sh
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/code-of-conduct.md
  release-tools/filter-junit.go
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/update-vendor.sh
  release-tools/util.sh
  release-tools/verify-go-version.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
  release-tools/verify-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#17 fix(filesystem_id): avoid filesystem_id 152.152 in exports
  pkg/volume/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#31 fix the file name for cloudbuild.yaml
  README.md
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
