Repository kubernetes-sigs/nfs-ganesha-server-and-external-provisioner, pull requests merged in 2021-11, with the labels that each got.

#74 Add clusterIP as variable
  charts/nfs-server-provisioner/templates/service.yaml
  charts/nfs-server-provisioner/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#75 Bump chart version
  charts/nfs-server-provisioner/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#62 Dockerfile: bump fedora to 35, and drop support for arm, but retain support for arm64/amd64
  .cloudbuild.sh
  .github/workflows/docker-build-test.yml
  Dockerfile
  Makefile
  deploy/docker/Dockerfile
  deploy/docker/arm/Dockerfile
Labels: approved, size/L, cncf-cla: yes, lgtm

#77 Increase cloudbuild timeout
  release-tools/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#76 Enable ppc64le and s390x
  .cloudbuild.sh
  .github/workflows/docker-build-test.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#80 Enable ppc64le and s390x in prow builds
  .prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#81 Attempt to decrease build times
  deploy/docker/Dockerfile
Labels: approved, cncf-cla: yes, size/S, lgtm

#82 feat(chart): allow configuration of k8s scheduling priority
  charts/nfs-server-provisioner/Chart.yaml
  charts/nfs-server-provisioner/README.md
  charts/nfs-server-provisioner/templates/priorityclass.yaml
  charts/nfs-server-provisioner/templates/statefulset.yaml
  charts/nfs-server-provisioner/values.yaml
Labels: approved, cncf-cla: yes, size/M, lgtm

#83 images: use k8s-staging-test-infra/gcb-docker-gcloud
  release-tools/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
