Repository kubernetes-sigs/nfs-ganesha-server-and-external-provisioner, pull requests merged in 2021-06, with the labels that each got.

#50 Add support for linux-arm64 image builds
  .cloudbuild.sh
  .prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#51 chore(doc): update references of container registry of nfs-provisioner from gcr.io to k8s.gcr.io
  deploy/helm/Chart.yaml
  deploy/helm/README.md
  deploy/helm/values.yaml
  deploy/kubernetes/deployment.yaml
  deploy/kubernetes/pod.yaml
  deploy/kubernetes/statefulset.yaml
  docs/deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#54 feat(helm): add github action for chart test
  .github/workflows/chart-lint-test.yml
  ct.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
