Repository kubernetes-sigs/nfs-ganesha-server-and-external-provisioner, pull requests merged in 2021-08, with the labels that each got.

#56 Replace Dockerfile by symlink
  Dockerfile
  deploy/docker/x86_64/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#58 Update github links referencing master to reference HEAD
  CHANGELOG.md
  README.md
  deploy/helm/Chart.yaml
  deploy/helm/README.md
  deploy/helm/values.yaml
Labels: approved, cncf-cla: yes, size/S, lgtm

#61 updated to v3.5
  deploy/docker/x86_64/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS
