Repository kubernetes-sigs/nfs-ganesha-server-and-external-provisioner, pull requests merged in 2023-01, with the labels that each got.

#107 Add persistence.existingClaim to nfs-ganesha-external-provisioner
  charts/nfs-server-provisioner/Chart.yaml
  charts/nfs-server-provisioner/README.md
  charts/nfs-server-provisioner/templates/statefulset.yaml
  charts/nfs-server-provisioner/values.yaml
Labels: approved, cncf-cla: yes, size/S, lgtm

#104 Improve reconnecting behaviour
  charts/nfs-server-provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#112 Authorize RBAC to use `scc/privileged`
  charts/nfs-server-provisioner/templates/clusterrole.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#113 Mention the Helm chart in deployment docs
  docs/deployment.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 Fix Execution on Fedora 36 and Kubernetes v1.24.3
  .github/workflows/docker-build.yml
  CHANGELOG.md
  charts/nfs-server-provisioner/Chart.yaml
  charts/nfs-server-provisioner/README.md
  charts/nfs-server-provisioner/values.yaml
  deploy/base/Dockerfile
  deploy/docker/Dockerfile
  deploy/kubernetes/deployment.yaml
  deploy/kubernetes/pod.yaml
  deploy/kubernetes/statefulset.yaml
  docs/deployment.md
  go.mod
  go.sum
  pkg/server/server.go
  pkg/volume/export.go
Labels: approved, cncf-cla: yes, size/M, lgtm

#116 Use HELM chart to configure container security contex
  charts/nfs-server-provisioner/Chart.yaml
  charts/nfs-server-provisioner/templates/statefulset.yaml
  charts/nfs-server-provisioner/values.yaml
Labels: approved, cncf-cla: yes, size/S, lgtm
